version: '3.7'

volumes:
    postgres:
    pgadmin:

services:
  database:
    container_name: hubla_db
    image: "postgres:12"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/data/postgres"
    volumes:
       - postgres:/data/postgres
       - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - hubla_net
  front:
    build:
      context: ./front
    ports:
      - "3000:3000"
    container_name: front
    stdin_open: true
    env_file:
      - ./front/.env.docker
    volumes:
       - ./front:/usr/src/app/front
       - /usr/src/app/front/node_modules
    networks:
      - hubla_net
    depends_on:
      - api
  api:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env.docker
    # Run a command against the development stage of the image
    depends_on:
      - database
    command: ./startup.sh
    ports:
      - "3333:3333"
    networks:
      - hubla_net
networks:
  hubla_net:
    driver: "bridge"
    
